---
title: "Htmlwidget Templates"
output: html_document
---

The following chart templates are currently provided:

- [BarCharts](http://ox-it.github.io/LiveData_htmlwidgets/charts/BarCharts), [StackedBarCharts](http://ox-it.github.io/LiveData_htmlwidgets/charts/StackedBarCharts), [LineCharts](http://ox-it.github.io/LiveData_htmlwidgets/charts/LineCharts)
- [Interactive Tables (Datatables)](http://ox-it.github.io/LiveData_htmlwidgets/datatable)
- Gauges
- Scattergeo, Choropleth
- Networks
- Timelines and Gantt Charts

Chart templates are organised in this repository as follows:

```
chartType
---------| index.html
---------| shiny_Folder
-----------------------| ui.R
-----------------------| server.R
```

The index.html file contains a very basic description of the chartType discussed in the templates, and instructions on how to construct the chartType with a variety of different libraries (where possible). This file can be viewed at the following address:

http://ox-it.github.io/LiveData_htmlwidgets/chartType

Where multiple libraries are capable of making comparable visualisations, a shiny app is provided to compare these at the following address:

https://livedataoxford.shinyapps.io/htmlwidget_template_chartType

Note that multiple shiny apps may be associated with one template, these may be documented within this repository or elsewhere but links to both documentation and parent Github repositories will be provided within the shiny app.