---
title: "Network Visualisations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# visNetwork

This is the best library.

## Edge tooltips

```{r visNetwork_edgelabels}
library(visNetwork)
library(htmltools)
edges <- data.frame(from = sample(1:10,8), to = sample(1:10, 8),
                    
  # length
  length = c(100,500),
  
  # width
  width = c(4,1),
  
  # arrows
  arrows = c("to", "from", "middle", "middle;to"),
  
  # dashes
  dashes = c(TRUE, FALSE),
  
  # tooltip (html or character)
  # title = paste("Edge", 1:8),
  
  title = rep(HTML(paste0(
    "<p>","First Line","</p>",
    "<p>","Second Line","</p>")), 8),
  
  # smooth
  smooth = c(FALSE, TRUE),
  
  # shadow
  shadow = c(FALSE, TRUE, FALSE, TRUE)) 

# head(edges)
#  from to  label length    arrows dashes  title smooth shadow
#    10  7 Edge 1    100        to   TRUE Edge 1  FALSE  FALSE
#     4 10 Edge 2    500      from  FALSE Edge 2   TRUE   TRUE

nodes <- data.frame(id = 1:10, group = c("A", "B"))
visNetwork(nodes, edges, height = "500px", width = "100%")
```

