---
title: "Villi Data Analysis"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import and Clean

```{r}
## Import
data_import <- read.csv(file = "villi-data.csv",skipNul = TRUE, stringsAsFactors = F)
## Drop those rows where count is NA
data_import <- data_import[!is.na(data_import$count),]
## =========================== Format Data =====================================
## ==============================================================================
library(lubridate)
data_import$timestamp <- dmy(data_import$timestamp)
gig_economy_data <- data_import
```

## Visualisations

This shows the whole dataset

```{r}
library(highcharter)
highchart() %>% 
  hc_title(text = "View of entire data") %>% 
  hc_tooltip(valueDecimals = 0) %>% 
  hc_add_series_times_values(gig_economy_data$timestamp,
                             gig_economy_data$count,
                             name = "Data")
```

Look only at "clerical and data entry" entries where status is "closed"

```{r}
clerical_data <- gig_economy_data[gig_economy_data$project_occupation == "Clerical and data entry" & gig_economy_data$status == "new",]
highchart() %>% 
  hc_title(text = "Counts of \"Clerical and Data Entry\" where status is new") %>% 
  hc_tooltip(valueDecimals = 0) %>% 
  hc_add_series_times_values(clerical_data$timestamp,
                             clerical_data$count,
                             name = "Count")
```

Multiple lines can easily be shown at once:

```{r}
new_data <- gig_economy_data[gig_economy_data$project_occupation == "Clerical and data entry" & gig_economy_data$status == "new",]
open_data <- gig_economy_data[gig_economy_data$project_occupation == "Clerical and data entry" & gig_economy_data$status == "open",]
highchart() %>% 
  hc_title(text = "Counts of \"Clerical and Data Entry\" where status is new") %>% 
  hc_tooltip(valueDecimals = 0) %>% 
  hc_add_series_times_values(new_data$timestamp,
                             new_data$count,
                             name = "Count") %>%
    hc_add_series_times_values(open_data$timestamp,
                             open_data$count,
                             name = "Count")
```

An alternative visualisation library is plotly:

```{r}
library(plotly)
new_data <- gig_economy_data[gig_economy_data$project_occupation == "Clerical and data entry" & gig_economy_data$status == "new",]
open_data <- gig_economy_data[gig_economy_data$project_occupation == "Clerical and data entry" & gig_economy_data$status == "open",]
plot_ly(
  data = new_data,
  x = timestamp,
  y = count, name = "foo"
) %>% add_trace(
  data = open_data,
  x = timestamp,
  y = count
)
```

Here's a basic shiny app that allows us to switch between different occupation types and visualisations

```{r}
library(shiny)
shinyApp(
  ui = fluidPage(sidebarLayout(
    sidebarPanel(
      selectInput(
        "selected_occupation",
        label = "Selected Occupation",
        choices = unique(gig_economy_data$project_occupation)
      ),
      selectInput(
        "selected_vizlibrary",
        label = "Visualisation Type",
        choices = c("Highchart", "Plotly")
      )
    ),
    mainPanel(uiOutput("output_plot"))
  )),
  server = function(input, output) {
    plot_data <- reactive({
      gig_economy_data[gig_economy_data$project_occupation == input$selected_occupation, ]
    })
    
    output$hchart <- renderHighchart({
      plot_data <- plot_data()
      
      open_data <- plot_data[plot_data$status == "open", ]
      closed_data <- plot_data[plot_data$status == "closed", ]
      
      highchart() %>%
        hc_chart(zoomType = "x") %>%
        hc_title(text = "Counts of \"Clerical and Data Entry\" where status is new") %>%
        hc_tooltip(valueDecimals = 0) %>%
        hc_add_series_times_values(open_data$timestamp,
                                   open_data$count,
                                   name = "Open Values") %>%
        hc_add_series_times_values(closed_data$timestamp,
                                   closed_data$count,
                                   name = "Closed Values")
    })
    
    output$plotly_chart <- renderPlotly({
      plot_data <- plot_data()
      
      open_data <- plot_data[plot_data$status == "open", ]
      closed_data <- plot_data[plot_data$status == "closed", ]
      
      plot_ly(
        data = open_data,
        x = timestamp,
        y = count, name = "Open"
      ) %>% add_trace(
        data = closed_data,
        x = timestamp,
        y = count, name = "Closed"
      )
    })
    
    output$output_plot <- renderUI({
      switch (input$selected_vizlibrary,
        "Highchart" = highchartOutput("hchart"),
        "Plotly" = plotlyOutput("plotly_chart")
      )
    })
  }
)
```













