---
title: "htmlwidgets Gaugues"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Knob (Not on CRAN)

https://github.com/htmlwidgets/knob

```{r}
library(shiny)
library(knob)

ui = shinyUI(fluidPage(
  sliderInput('value', 'Value', 0, 200, 50),
  sliderInput('angleArc', 'Arc Angle', 45, 360, 180),
  knobOutput('gauge')
))

server = function(input, output){
  output$gauge <- renderKnob(knob(
    value = input$value,
    min = 0,
    max = 200,
    angleArc = input$angleArc,
    angleOffset = -90,
    fgColor="#66CC66"
  ))
}

shinyApp(ui = ui, server = server)
```

# justGauge (Not on CRAN; No longer works)

```{r}
library(htmlwidgets)
library(justGage)
k1 = justgage('My Gauge', 20, 0, 100, label = 'New')
k1
```

# Highcharts (CRAN)

## Solid Gauge

```{r highchart_solidgauge}
hc <- highchart() %>%
  hc_chart(type = "solidgauge") %>%
  hc_title(text = "A highcharter chart") %>%
  hc_pane(startAngle = -150,
          endAngle = 150) %>%
  hc_yAxis(
    min = 0,
    max = 200
  )


hc %>%  hc_add_series(data = c(0,100))

hc %>%  hc_add_series(data = c(90), name = "Downloads")

hc %>%  hc_add_series(data = 90, name = "Downloads")
```

## Angular Gauage

There appears to be a bug at present which I have reported: https://github.com/jbkunst/highcharter/issues/118

```{r highchart_simple}
hc <- highchart() %>%
  hc_chart(type = "gauge") %>%
  hc_title(text = "A highcharter chart") %>%
  hc_pane(startAngle = -90,
          endAngle = 90) %>%
  hc_yAxis(
    min = 0,
    max = 100,
    minorTickInterval = 'auto',
    minorTickWidth = 1,
    minorTickLength = 10,
    minorTickPosition = 'inside',
    minorTickColor = '#666',
    tickPixelInterval = 30,
    tickWidth = 2,
    tickPosition = 'inside',
    tickLength = 10,
    tickColor = '#666',
    labels = list(step = 2,
                  rotation = 'auto')
    # plotBands = list(from = 0,
    #                  to = 120,
    #                  color = "#55BF3B")
  )


hc %>%  hc_add_series(data = c(90,100))

hc %>%  hc_add_series(data = c(90), name = "Downloads")

hc %>%  hc_add_series(data = 90, name = "Downloads")
```


```{r highchart_fancy}
library(highcharter)

hc <- highchart() %>%
  hc_chart(type = "gauge") %>%
  hc_title(text = "A highcharter chart") %>%
  hc_pane(startAngle = -150,
          endAngle = 150) %>%
  hc_yAxis(
    min = 0,
    max = 200,
    minorTickInterval = 'auto',
    minorTickWidth = 1,
    minorTickLength = 10,
    minorTickPosition = 'inside',
    minorTickColor = '#666',
    tickPixelInterval = 30,
    tickWidth = 2,
    tickPosition = 'inside',
    tickLength = 10,
    tickColor = '#666',
    labels = list(step = 2,
                  rotation = 'auto')
    # plotBands = list(from = 0,
    #                  to = 120,
    #                  color = "#55BF3B")
  ) %>%
  hc_add_series(data = c(90),
                name = "Downloads")


hc

```



