---
title: "htmlwidget Libraries Overview"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r xlsx_2_csv}
xlsx_convert_import <- function(inputFile = NA, outputFile = NA){
  if(file.exists(outputFile)){
    imported_data <<- read.csv(outputFile)
  } else {
    library(xlsx)
    xlsx_import <- read.xlsx(inputFile, sheetIndex = 1)
    write.csv(xlsx_import, file = outputFile, row.names = FALSE)
    remove(xlsx_import)
    imported_data <<- read.csv(outputFile)
  }
}

```

## Overview of Document

This document considers only those htmlwidget libraries which are available on CRAN, only a few are covered in detail - submissions are welcome.

## Visualisations by Library

```{r viz_by_library_glyphicons}
library(DT)
library(shiny)
viz_by_library <- xlsx_convert_import(inputFile = "chart-type_htmlwidget-libraries.xlsx", outputFile = "chart-type_htmlwidget-libraries.csv")
viz_by_library

# viz_by_library[viz_by_library==1] <- "<span class='glyphicon glyphicon-ok' aria-hidden='true'></span>"
# viz_by_library[viz_by_library==0] <- "<span class='glyphicon glyphicon-remove' aria-hidden='true'></span>"
# viz_by_library[is.na(viz_by_library)] <- "<span class='glyphicon glyphicon-question-sign' aria-hidden='true'></span>"

viz_by_library[viz_by_library==1] <- 'YES'
viz_by_library[viz_by_library==0] <- "NO"
viz_by_library[is.na(viz_by_library)] <- "?"
viz_by_library[viz_by_library=="Future"] <- "FUTURE"

viz_types <- colnames(viz_by_library)[2:length(colnames(viz_by_library))]

shinyApp(
  ui = fluidPage(
    # uiOutput("column_selector"),
    
    # wellPanel(
    #   fluidRow(
    #     column(
    #       checkboxGroupInput("selected_comparitiveVizs", label = "Select Visualisations",
    #                    choices = as.list(setNames(viz_types, gsub("[.]"," ", viz_types))),
    #                    inline = FALSE,
    #                    selected = c("Barchart","Gantt.Chart","Choropleth")),
    #       width = 4
    #     ),
    #     column(
    #     checkboxGroupInput("selected_3DVizs", label = "Select Visualisations",
    #                    choices = as.list(setNames(viz_types, gsub("[.]"," ", viz_types))),
    #                    inline = FALSE,
    #                    selected = c("Barchart","Gantt.Chart","Choropleth")), width = 4)
    #     
    #     
    #   )
    # ),
    
    sidebarLayout(
      sidebarPanel(
        checkboxGroupInput("selected_columns", label = "Select Visualisations",
                       choices = as.list(setNames(viz_types, gsub("[.]"," ", viz_types))),
                       inline = FALSE,
                       selected = c("Barchart","Gantt.Chart","Choropleth"))
      ),
      mainPanel(
        dataTableOutput("summary")
      )
    )
  ),
  server = function(input, output){
    output$summary <- renderDataTable({
      
      datatable(viz_by_library[,c("Library",input$selected_columns)],
                 filter = list(position = 'top', clear = TRUE, plain = TRUE),
                rownames = F,options = list(paging = FALSE, searching = FALSE)
      )
      
    })
  }
)


```

