---
title: "Server-Side DataTable"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Shiny App

Following guide here - http://rstudio.github.io/DT/server.html

```{r basic_server_side_DT}
library(DT)
library(shiny)
ui <- fluidPage(
  title = 'Use the DT package in shiny',
  h1('A Table Using Client-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_a')),
    column(2)
  ),
  h1('A Table Using Server-side Processing'),
  fluidRow(
    column(2),
    column(8, DT::dataTableOutput('tbl_b')),
    column(2)
  )
)

server <- function(input, output, session) {
  output$tbl_a = DT::renderDataTable(iris, server = FALSE)
  output$tbl_b = DT::renderDataTable(iris)
}

shinyApp(ui = ui, server = server)

```

### JSONP Example

```{r jsonp_DT}
library(DT)
library(shiny)
ui <- fluidPage(
  h1('A Table Using Server-side Processing'),
  DT::dataTableOutput('server_queried_DT')
)

server <- function(input, output, session) {
  
  employee <- data.frame(
    "First name" = character(), "Last name" = character(), "Position" = character(),
    "Office" = character(), "Start date" = character(), "Salary" = numeric(),
    check.names = FALSE
  )
  
  output$tbl_a = DT::renderDataTable(iris, server = FALSE)
  output$server_queried_DT = DT::renderDataTable(employee, rownames = FALSE, options = list(
    ajax = list(
      serverSide = TRUE, processing = TRUE,
      url = 'http://datatables.net/examples/server_side/scripts/jsonp.php',
      dataType = 'jsonp'
    )
  ))
}

shinyApp(ui = ui, server = server)
```



